### ISSUE TITLE
Subcomponent: Gallery container

### ISSUE THREAD

**Issue by ford-jones** [ford-jones/redican-framing#47]
1. Create a component which consumes props inherited from its' parent container (`Gallery`) and displays the data by calling upon the gallery middleware and passing it the data.

2. The images should take up about 60% of the screen and cycle through on a timer. 

3. There should also be forward and back buttons which allow you to cycle through the gallery manually.

**Comment by xavier-fenton** [comment]
Still need to = **2. The images should take up about 60% of the screen and cycle through on a timer.**
